ivshmem:
    - '[Ii][Vv][Ss][Hh][Mm][Ee][Mm]'
Balloon:
    - '[Bb][Aa][Ll][Ll][Oo][Oo][Nn]'
NetKVM:
    - '[Nn][Ee][Tt](\s|-)*[Kk][Vv][Mm]'
Spice:
    - '[Ss][Pp][Ii][Cc][Ee]'
vioscsi:
    - 'vioscsi'
viosock:
    - 'viosock'
viostor:
    - 'viostor'
virtio-fs:
    - 'virtio-fs'
virtio-gpu:
    - 'virtio-gpu'
virtio-input:
    - 'virtio-input'
virtio-mem:
    - 'virtio-mem'
    
