ivshmem:
    - 'ivshmem'
Balloon:
    - 'Balloon'
NetKVM:
    - 'NetKVM'
Spice:
    - '[Ss][Pp][Ii][Cc][Ee]'
vioscsi:
    - 'vioscsi'
viosock:
    - 'viosock'
viostor:
    - 'viostor'
virtio-fs:
    - 'virtio-fs'
virtio-gpu:
    - 'virtio-gpu'
virtio-input:
    - 'virtio-input'
virtio-mem:
    - 'virtio-mem'
    
